"""initial import and curriculum schema

Revision ID: 00588ca0728a
Revises:
Create Date: 2026-07-15 21:48:45.869292
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "00588ca0728a"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_courses")),
    )
    op.create_index(op.f("ix_courses_code"), "courses", ["code"], unique=True)
    op.create_index(
        op.f("ix_courses_normalized_name"), "courses", ["normalized_name"], unique=False
    )
    op.create_table(
        "import_files",
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("stored_path", sa.String(length=1024), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_files")),
        sa.UniqueConstraint("sha256", "original_filename", name="uq_import_file_hash_name"),
    )
    op.create_index(op.f("ix_import_files_sha256"), "import_files", ["sha256"], unique=False)
    op.create_table(
        "subjects",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
    )
    op.create_index(op.f("ix_subjects_code"), "subjects", ["code"], unique=True)
    op.create_index(
        op.f("ix_subjects_normalized_name"), "subjects", ["normalized_name"], unique=False
    )
    op.create_table(
        "teachers",
        sa.Column("canonical_name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teachers")),
    )
    op.create_index(
        op.f("ix_teachers_normalized_name"), "teachers", ["normalized_name"], unique=False
    )
    op.create_table(
        "terms",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("term_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terms")),
    )
    op.create_index(op.f("ix_terms_code"), "terms", ["code"], unique=True)
    op.create_table(
        "curriculum_versions",
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("admission_year_start", sa.Integer(), nullable=True),
        sa.Column("admission_year_end", sa.Integer(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_curriculum_versions_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_versions")),
        sa.UniqueConstraint("course_id", "version", name="uq_curriculum_course_version"),
    )
    op.create_index(
        op.f("ix_curriculum_versions_course_id"), "curriculum_versions", ["course_id"], unique=False
    )
    op.create_index(
        "ix_curriculum_versions_validity",
        "curriculum_versions",
        ["course_id", "valid_from", "valid_until"],
        unique=False,
    )
    op.create_index(
        op.f("ix_curriculum_versions_version"), "curriculum_versions", ["version"], unique=False
    )
    op.create_table(
        "external_teacher_identifiers",
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_external_teacher_identifiers_teacher_id_teachers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_teacher_identifiers")),
        sa.UniqueConstraint("provider", "external_id", name="uq_teacher_external_provider_id"),
    )
    op.create_index(
        op.f("ix_external_teacher_identifiers_teacher_id"),
        "external_teacher_identifiers",
        ["teacher_id"],
        unique=False,
    )
    op.create_table(
        "import_batches",
        sa.Column("import_file_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=True),
        sa.Column("comparison_batch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "COMPLETED_WITH_ISSUES",
                "FAILED",
                name="importstatus",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("source_sheet", sa.String(length=255), nullable=True),
        sa.Column("parser_config", sa.JSON(), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("imported_rows", sa.Integer(), nullable=False),
        sa.Column("invalid_rows", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("added_sections", sa.Integer(), nullable=False),
        sa.Column("changed_sections", sa.Integer(), nullable=False),
        sa.Column("removed_sections", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["comparison_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_batches_comparison_batch_id_import_batches"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["import_file_id"],
            ["import_files.id"],
            name=op.f("fk_import_batches_import_file_id_import_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
            name=op.f("fk_import_batches_term_id_terms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_batches")),
    )
    op.create_index(
        op.f("ix_import_batches_import_file_id"), "import_batches", ["import_file_id"], unique=False
    )
    op.create_index(op.f("ix_import_batches_term_id"), "import_batches", ["term_id"], unique=False)
    op.create_table(
        "teacher_aliases",
        sa.Column("teacher_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("normalized_name", sa.String(length=512), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "MATCHED",
                "PENDING_REVIEW",
                "IGNORED",
                name="teacheraliasstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_aliases_teacher_id_teachers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_aliases")),
        sa.UniqueConstraint("teacher_id", "normalized_name", name="uq_teacher_alias_teacher_name"),
    )
    op.create_index(
        "ix_teacher_aliases_normalized_status",
        "teacher_aliases",
        ["normalized_name", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_aliases_teacher_id"), "teacher_aliases", ["teacher_id"], unique=False
    )
    op.create_table(
        "course_curriculum_subjects",
        sa.Column("curriculum_version_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "MANDATORY",
                "LIMITED",
                "FREE",
                "NOT_APPLICABLE",
                name="curriculumcategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "category_source",
            sa.Enum(
                "EXPLICIT",
                "DERIVED_RULE",
                name="curriculumcategorysource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ideal_term", sa.Integer(), nullable=True),
        sa.Column("recommended_term", sa.Integer(), nullable=True),
        sa.Column("credits", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_version_id"],
            ["curriculum_versions.id"],
            name=op.f("fk_course_curriculum_subjects_curriculum_version_id_curriculum_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_course_curriculum_subjects_subject_id_subjects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_curriculum_subjects")),
        sa.UniqueConstraint("curriculum_version_id", "subject_id", name="uq_curriculum_subject"),
    )
    op.create_index(
        op.f("ix_course_curriculum_subjects_curriculum_version_id"),
        "course_curriculum_subjects",
        ["curriculum_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_course_curriculum_subjects_subject_id"),
        "course_curriculum_subjects",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        "ix_curriculum_subjects_category",
        "course_curriculum_subjects",
        ["curriculum_version_id", "category"],
        unique=False,
    )
    op.create_table(
        "curriculum_requirements",
        sa.Column("curriculum_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "MANDATORY",
                "LIMITED",
                "FREE",
                "NOT_APPLICABLE",
                name="curriculumcategory",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("minimum_credits", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("minimum_subjects", sa.Integer(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_version_id"],
            ["curriculum_versions.id"],
            name=op.f("fk_curriculum_requirements_curriculum_version_id_curriculum_versions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_requirements")),
    )
    op.create_index(
        op.f("ix_curriculum_requirements_curriculum_version_id"),
        "curriculum_requirements",
        ["curriculum_version_id"],
        unique=False,
    )
    op.create_table(
        "import_errors",
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("WARNING", "ERROR", name="importissuelevel", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=True),
        sa.Column("field", sa.String(length=100), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("raw_data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_import_errors_import_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_errors")),
    )
    op.create_index(
        "ix_import_errors_batch_level", "import_errors", ["import_batch_id", "level"], unique=False
    )
    op.create_index(
        op.f("ix_import_errors_import_batch_id"), "import_errors", ["import_batch_id"], unique=False
    )
    op.create_table(
        "sections",
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("first_seen_batch_id", sa.Uuid(), nullable=False),
        sa.Column("last_seen_batch_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("class_group", sa.String(length=32), nullable=True),
        sa.Column("display_name", sa.String(length=768), nullable=True),
        sa.Column("campus", sa.String(length=32), nullable=True),
        sa.Column("shift", sa.String(length=32), nullable=True),
        sa.Column("total_seats", sa.Integer(), nullable=True),
        sa.Column("reserved_seats", sa.Integer(), nullable=True),
        sa.Column("workload_code", sa.String(length=32), nullable=True),
        sa.Column("theory_hours", sa.Integer(), nullable=True),
        sa.Column("practice_hours", sa.Integer(), nullable=True),
        sa.Column("individual_hours", sa.Integer(), nullable=True),
        sa.Column("extension_hours", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_sections_first_seen_batch_id_import_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_sections_last_seen_batch_id_import_batches"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_sections_subject_id_subjects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"], ["terms.id"], name=op.f("fk_sections_term_id_terms"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("term_id", "code", name="uq_section_term_code"),
    )
    op.create_index(op.f("ix_sections_campus"), "sections", ["campus"], unique=False)
    op.create_index(op.f("ix_sections_code"), "sections", ["code"], unique=False)
    op.create_index(op.f("ix_sections_is_active"), "sections", ["is_active"], unique=False)
    op.create_index(op.f("ix_sections_shift"), "sections", ["shift"], unique=False)
    op.create_index(op.f("ix_sections_subject_id"), "sections", ["subject_id"], unique=False)
    op.create_index("ix_sections_term_active", "sections", ["term_id", "is_active"], unique=False)
    op.create_index(op.f("ix_sections_term_id"), "sections", ["term_id"], unique=False)
    op.create_index("ix_sections_term_subject", "sections", ["term_id", "subject_id"], unique=False)
    op.create_table(
        "section_course_offerings",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("reserved_seats", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_section_course_offerings_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_section_course_offerings_section_id_sections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_section_course_offerings")),
        sa.UniqueConstraint("section_id", "course_id", name="uq_section_course_offering"),
    )
    op.create_index(
        op.f("ix_section_course_offerings_course_id"),
        "section_course_offerings",
        ["course_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_section_course_offerings_section_id"),
        "section_course_offerings",
        ["section_id"],
        unique=False,
    )
    op.create_table(
        "section_meetings",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("campus", sa.String(length=32), nullable=True),
        sa.Column("classroom", sa.String(length=255), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum(
                "WEEKLY",
                "BIWEEKLY_I",
                "BIWEEKLY_II",
                "OTHER",
                name="meetingfrequency",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "meeting_type",
            sa.Enum("THEORY", "PRACTICE", name="meetingtype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_section_meetings_section_id_sections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_section_meetings")),
    )
    op.create_index(
        op.f("ix_section_meetings_section_id"), "section_meetings", ["section_id"], unique=False
    )
    op.create_index(
        "ix_section_meetings_weekday_time",
        "section_meetings",
        ["weekday", "start_time"],
        unique=False,
    )
    op.create_table(
        "section_revisions",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("import_batch_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("changed_fields", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"],
            ["import_batches.id"],
            name=op.f("fk_section_revisions_import_batch_id_import_batches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_section_revisions_section_id_sections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_section_revisions")),
        sa.UniqueConstraint("section_id", "import_batch_id", name="uq_section_revision_batch"),
    )
    op.create_index(
        op.f("ix_section_revisions_fingerprint"), "section_revisions", ["fingerprint"], unique=False
    )
    op.create_index(
        op.f("ix_section_revisions_import_batch_id"),
        "section_revisions",
        ["import_batch_id"],
        unique=False,
    )
    op.create_index(
        "ix_section_revisions_section_created",
        "section_revisions",
        ["section_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_section_revisions_section_id"), "section_revisions", ["section_id"], unique=False
    )
    op.create_table(
        "section_teachers",
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("THEORY", "PRACTICE", name="teacherrole", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_section_teachers_section_id_sections"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_section_teachers_teacher_id_teachers"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_section_teachers")),
        sa.UniqueConstraint(
            "section_id", "role", "position", name="uq_section_teacher_role_position"
        ),
    )
    op.create_index(
        op.f("ix_section_teachers_section_id"), "section_teachers", ["section_id"], unique=False
    )
    op.create_index(
        op.f("ix_section_teachers_teacher_id"), "section_teachers", ["teacher_id"], unique=False
    )
    op.create_index(
        "ix_section_teachers_teacher_role", "section_teachers", ["teacher_id", "role"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_section_teachers_teacher_role", table_name="section_teachers")
    op.drop_index(op.f("ix_section_teachers_teacher_id"), table_name="section_teachers")
    op.drop_index(op.f("ix_section_teachers_section_id"), table_name="section_teachers")
    op.drop_table("section_teachers")
    op.drop_index(op.f("ix_section_revisions_section_id"), table_name="section_revisions")
    op.drop_index("ix_section_revisions_section_created", table_name="section_revisions")
    op.drop_index(op.f("ix_section_revisions_import_batch_id"), table_name="section_revisions")
    op.drop_index(op.f("ix_section_revisions_fingerprint"), table_name="section_revisions")
    op.drop_table("section_revisions")
    op.drop_index("ix_section_meetings_weekday_time", table_name="section_meetings")
    op.drop_index(op.f("ix_section_meetings_section_id"), table_name="section_meetings")
    op.drop_table("section_meetings")
    op.drop_index(
        op.f("ix_section_course_offerings_section_id"), table_name="section_course_offerings"
    )
    op.drop_index(
        op.f("ix_section_course_offerings_course_id"), table_name="section_course_offerings"
    )
    op.drop_table("section_course_offerings")
    op.drop_index("ix_sections_term_subject", table_name="sections")
    op.drop_index(op.f("ix_sections_term_id"), table_name="sections")
    op.drop_index("ix_sections_term_active", table_name="sections")
    op.drop_index(op.f("ix_sections_subject_id"), table_name="sections")
    op.drop_index(op.f("ix_sections_shift"), table_name="sections")
    op.drop_index(op.f("ix_sections_is_active"), table_name="sections")
    op.drop_index(op.f("ix_sections_code"), table_name="sections")
    op.drop_index(op.f("ix_sections_campus"), table_name="sections")
    op.drop_table("sections")
    op.drop_index(op.f("ix_import_errors_import_batch_id"), table_name="import_errors")
    op.drop_index("ix_import_errors_batch_level", table_name="import_errors")
    op.drop_table("import_errors")
    op.drop_index(
        op.f("ix_curriculum_requirements_curriculum_version_id"),
        table_name="curriculum_requirements",
    )
    op.drop_table("curriculum_requirements")
    op.drop_index("ix_curriculum_subjects_category", table_name="course_curriculum_subjects")
    op.drop_index(
        op.f("ix_course_curriculum_subjects_subject_id"), table_name="course_curriculum_subjects"
    )
    op.drop_index(
        op.f("ix_course_curriculum_subjects_curriculum_version_id"),
        table_name="course_curriculum_subjects",
    )
    op.drop_table("course_curriculum_subjects")
    op.drop_index(op.f("ix_teacher_aliases_teacher_id"), table_name="teacher_aliases")
    op.drop_index("ix_teacher_aliases_normalized_status", table_name="teacher_aliases")
    op.drop_table("teacher_aliases")
    op.drop_index(op.f("ix_import_batches_term_id"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_import_file_id"), table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index(
        op.f("ix_external_teacher_identifiers_teacher_id"),
        table_name="external_teacher_identifiers",
    )
    op.drop_table("external_teacher_identifiers")
    op.drop_index(op.f("ix_curriculum_versions_version"), table_name="curriculum_versions")
    op.drop_index("ix_curriculum_versions_validity", table_name="curriculum_versions")
    op.drop_index(op.f("ix_curriculum_versions_course_id"), table_name="curriculum_versions")
    op.drop_table("curriculum_versions")
    op.drop_index(op.f("ix_terms_code"), table_name="terms")
    op.drop_table("terms")
    op.drop_index(op.f("ix_teachers_normalized_name"), table_name="teachers")
    op.drop_table("teachers")
    op.drop_index(op.f("ix_subjects_normalized_name"), table_name="subjects")
    op.drop_index(op.f("ix_subjects_code"), table_name="subjects")
    op.drop_table("subjects")
    op.drop_index(op.f("ix_import_files_sha256"), table_name="import_files")
    op.drop_table("import_files")
    op.drop_index(op.f("ix_courses_normalized_name"), table_name="courses")
    op.drop_index(op.f("ix_courses_code"), table_name="courses")
    op.drop_table("courses")
    # ### end Alembic commands ###
