"""add derived grade statistics

Revision ID: 1acc84acc4a0
Revises: 1fecfaf3a22e
Create Date: 2026-07-16 00:57:23.155379
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1acc84acc4a0"
down_revision: str | None = "1fecfaf3a22e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statistics_builds",
        sa.Column("prior_weight", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("grade_weights", sa.JSON(), nullable=False),
        sa.Column("teacher_statistics_count", sa.Integer(), nullable=False),
        sa.Column("subject_statistics_count", sa.Integer(), nullable=False),
        sa.Column("teacher_subject_statistics_count", sa.Integer(), nullable=False),
        sa.Column("recent_history_available", sa.Boolean(), nullable=False),
        sa.Column("source_snapshot_counts", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statistics_builds")),
    )
    op.create_index(
        op.f("ix_statistics_builds_computed_at"), "statistics_builds", ["computed_at"], unique=False
    )
    op.create_table(
        "teacher_term_statistics",
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("external_teacher_id", sa.String(length=255), nullable=False),
        sa.Column("external_subject_id", sa.String(length=255), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("grade_counts", sa.JSON(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("effective_sample_size", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("raw_a_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_a_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_ab_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_ab_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_failure_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_failure_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_fo_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_fo_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_mean_grade", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_mean_grade", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "NONE",
                "LOW",
                "MEDIUM",
                "HIGH",
                name="statisticsconfidence",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("prior_weight", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("reference_rates", sa.JSON(), nullable=False),
        sa.Column("grade_weights", sa.JSON(), nullable=False),
        sa.Column("source_fetched_at", sa.DateTime(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_teacher_term_statistics_subject_id_subjects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_term_statistics_teacher_id_teachers"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
            name=op.f("fk_teacher_term_statistics_term_id_terms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_term_statistics")),
    )
    op.create_index(
        op.f("ix_teacher_term_statistics_computed_at"),
        "teacher_term_statistics",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_term_statistics_external_subject_id"),
        "teacher_term_statistics",
        ["external_subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_term_statistics_external_teacher_id"),
        "teacher_term_statistics",
        ["external_teacher_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_term_statistics_source_fetched_at"),
        "teacher_term_statistics",
        ["source_fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_term_statistics_subject_id"),
        "teacher_term_statistics",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_term_statistics_teacher_id"),
        "teacher_term_statistics",
        ["teacher_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_term_statistics_term_id"),
        "teacher_term_statistics",
        ["term_id"],
        unique=False,
    )
    op.create_index(
        "uq_teacher_term_statistics_external",
        "teacher_term_statistics",
        ["external_teacher_id", "external_subject_id", "term_id"],
        unique=True,
    )
    op.create_table(
        "subject_statistics",
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("external_subject_id", sa.String(length=255), nullable=False),
        sa.Column("source_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("grade_counts", sa.JSON(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("effective_sample_size", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("raw_a_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_a_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_ab_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_ab_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_failure_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_failure_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_fo_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_fo_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_mean_grade", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_mean_grade", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "NONE",
                "LOW",
                "MEDIUM",
                "HIGH",
                name="statisticsconfidence",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("prior_weight", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("reference_rates", sa.JSON(), nullable=False),
        sa.Column("grade_weights", sa.JSON(), nullable=False),
        sa.Column("source_fetched_at", sa.DateTime(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["subject_review_snapshots.id"],
            name=op.f("fk_subject_statistics_source_snapshot_id_subject_review_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_subject_statistics_subject_id_subjects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subject_statistics")),
    )
    op.create_index(
        op.f("ix_subject_statistics_computed_at"),
        "subject_statistics",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subject_statistics_external_subject_id"),
        "subject_statistics",
        ["external_subject_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_subject_statistics_source_fetched_at"),
        "subject_statistics",
        ["source_fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subject_statistics_source_snapshot_id"),
        "subject_statistics",
        ["source_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subject_statistics_subject_id"), "subject_statistics", ["subject_id"], unique=False
    )
    op.create_table(
        "teacher_statistics",
        sa.Column("teacher_id", sa.Uuid(), nullable=True),
        sa.Column("external_teacher_id", sa.String(length=255), nullable=False),
        sa.Column("source_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("grade_counts", sa.JSON(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("effective_sample_size", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("raw_a_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_a_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_ab_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_ab_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_failure_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_failure_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_fo_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_fo_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_mean_grade", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_mean_grade", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "NONE",
                "LOW",
                "MEDIUM",
                "HIGH",
                name="statisticsconfidence",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("prior_weight", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("reference_rates", sa.JSON(), nullable=False),
        sa.Column("grade_weights", sa.JSON(), nullable=False),
        sa.Column("source_fetched_at", sa.DateTime(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["teacher_review_snapshots.id"],
            name=op.f("fk_teacher_statistics_source_snapshot_id_teacher_review_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_statistics_teacher_id_teachers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_statistics")),
    )
    op.create_index(
        op.f("ix_teacher_statistics_computed_at"),
        "teacher_statistics",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_statistics_external_teacher_id"),
        "teacher_statistics",
        ["external_teacher_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_teacher_statistics_source_fetched_at"),
        "teacher_statistics",
        ["source_fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_statistics_source_snapshot_id"),
        "teacher_statistics",
        ["source_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_statistics_teacher_id"), "teacher_statistics", ["teacher_id"], unique=False
    )
    op.create_table(
        "teacher_subject_statistics",
        sa.Column("teacher_id", sa.Uuid(), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("external_teacher_id", sa.String(length=255), nullable=False),
        sa.Column("external_subject_id", sa.String(length=255), nullable=False),
        sa.Column("source_teacher_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("source_subject_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("grade_counts", sa.JSON(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("effective_sample_size", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("raw_a_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_a_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_ab_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_ab_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_failure_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_failure_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_fo_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_fo_rate", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("raw_mean_grade", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("adjusted_mean_grade", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum(
                "NONE",
                "LOW",
                "MEDIUM",
                "HIGH",
                name="statisticsconfidence",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("prior_weight", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("reference_rates", sa.JSON(), nullable=False),
        sa.Column("grade_weights", sa.JSON(), nullable=False),
        sa.Column("source_fetched_at", sa.DateTime(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_subject_snapshot_id"],
            ["subject_review_snapshots.id"],
            name=op.f(
                "fk_teacher_subject_statistics_source_subject_snapshot_id_subject_review_snapshots"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_teacher_snapshot_id"],
            ["teacher_review_snapshots.id"],
            name=op.f(
                "fk_teacher_subject_statistics_source_teacher_snapshot_id_teacher_review_snapshots"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_teacher_subject_statistics_subject_id_subjects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_subject_statistics_teacher_id_teachers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_subject_statistics")),
    )
    op.create_index(
        op.f("ix_teacher_subject_statistics_computed_at"),
        "teacher_subject_statistics",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subject_statistics_external_subject_id"),
        "teacher_subject_statistics",
        ["external_subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subject_statistics_external_teacher_id"),
        "teacher_subject_statistics",
        ["external_teacher_id"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_subject_statistics_internal",
        "teacher_subject_statistics",
        ["teacher_id", "subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subject_statistics_source_fetched_at"),
        "teacher_subject_statistics",
        ["source_fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subject_statistics_source_subject_snapshot_id"),
        "teacher_subject_statistics",
        ["source_subject_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subject_statistics_source_teacher_snapshot_id"),
        "teacher_subject_statistics",
        ["source_teacher_snapshot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subject_statistics_subject_id"),
        "teacher_subject_statistics",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_subject_statistics_teacher_id"),
        "teacher_subject_statistics",
        ["teacher_id"],
        unique=False,
    )
    op.create_index(
        "uq_teacher_subject_statistics_external",
        "teacher_subject_statistics",
        ["external_teacher_id", "external_subject_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_teacher_subject_statistics_external", table_name="teacher_subject_statistics")
    op.drop_index(
        op.f("ix_teacher_subject_statistics_teacher_id"), table_name="teacher_subject_statistics"
    )
    op.drop_index(
        op.f("ix_teacher_subject_statistics_subject_id"), table_name="teacher_subject_statistics"
    )
    op.drop_index(
        op.f("ix_teacher_subject_statistics_source_teacher_snapshot_id"),
        table_name="teacher_subject_statistics",
    )
    op.drop_index(
        op.f("ix_teacher_subject_statistics_source_subject_snapshot_id"),
        table_name="teacher_subject_statistics",
    )
    op.drop_index(
        op.f("ix_teacher_subject_statistics_source_fetched_at"),
        table_name="teacher_subject_statistics",
    )
    op.drop_index("ix_teacher_subject_statistics_internal", table_name="teacher_subject_statistics")
    op.drop_index(
        op.f("ix_teacher_subject_statistics_external_teacher_id"),
        table_name="teacher_subject_statistics",
    )
    op.drop_index(
        op.f("ix_teacher_subject_statistics_external_subject_id"),
        table_name="teacher_subject_statistics",
    )
    op.drop_index(
        op.f("ix_teacher_subject_statistics_computed_at"), table_name="teacher_subject_statistics"
    )
    op.drop_table("teacher_subject_statistics")
    op.drop_index(op.f("ix_teacher_statistics_teacher_id"), table_name="teacher_statistics")
    op.drop_index(op.f("ix_teacher_statistics_source_snapshot_id"), table_name="teacher_statistics")
    op.drop_index(op.f("ix_teacher_statistics_source_fetched_at"), table_name="teacher_statistics")
    op.drop_index(
        op.f("ix_teacher_statistics_external_teacher_id"), table_name="teacher_statistics"
    )
    op.drop_index(op.f("ix_teacher_statistics_computed_at"), table_name="teacher_statistics")
    op.drop_table("teacher_statistics")
    op.drop_index(op.f("ix_subject_statistics_subject_id"), table_name="subject_statistics")
    op.drop_index(op.f("ix_subject_statistics_source_snapshot_id"), table_name="subject_statistics")
    op.drop_index(op.f("ix_subject_statistics_source_fetched_at"), table_name="subject_statistics")
    op.drop_index(
        op.f("ix_subject_statistics_external_subject_id"), table_name="subject_statistics"
    )
    op.drop_index(op.f("ix_subject_statistics_computed_at"), table_name="subject_statistics")
    op.drop_table("subject_statistics")
    op.drop_index("uq_teacher_term_statistics_external", table_name="teacher_term_statistics")
    op.drop_index(op.f("ix_teacher_term_statistics_term_id"), table_name="teacher_term_statistics")
    op.drop_index(
        op.f("ix_teacher_term_statistics_teacher_id"), table_name="teacher_term_statistics"
    )
    op.drop_index(
        op.f("ix_teacher_term_statistics_subject_id"), table_name="teacher_term_statistics"
    )
    op.drop_index(
        op.f("ix_teacher_term_statistics_source_fetched_at"), table_name="teacher_term_statistics"
    )
    op.drop_index(
        op.f("ix_teacher_term_statistics_external_teacher_id"), table_name="teacher_term_statistics"
    )
    op.drop_index(
        op.f("ix_teacher_term_statistics_external_subject_id"), table_name="teacher_term_statistics"
    )
    op.drop_index(
        op.f("ix_teacher_term_statistics_computed_at"), table_name="teacher_term_statistics"
    )
    op.drop_table("teacher_term_statistics")
    op.drop_index(op.f("ix_statistics_builds_computed_at"), table_name="statistics_builds")
    op.drop_table("statistics_builds")
    # ### end Alembic commands ###
