"""add student academic profiles

Revision ID: 83481302fee5
Revises: 00588ca0728a
Create Date: 2026-07-15 22:42:24.288337
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "83481302fee5"
down_revision: str | None = "00588ca0728a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_profiles",
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("admission_year", sa.Integer(), nullable=False),
        sa.Column("admission_shift", sa.String(length=32), nullable=True),
        sa.Column("campus", sa.String(length=32), nullable=True),
        sa.Column("cr", sa.Numeric(precision=6, scale=4), nullable=True),
        sa.Column("accumulated_credits", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column(
            "course_strategy",
            sa.Enum(
                "PRIMARY_COURSE",
                "MAXIMIZE_ANY_COURSE_PROGRESS",
                "MAXIMIZE_ALL_COURSES_PROGRESS",
                "WEIGHTED_COURSES",
                name="coursestrategy",
                native_enum=False,
                length=48,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_profiles")),
    )
    op.create_table(
        "student_completed_subjects",
        sa.Column("student_profile_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=True),
        sa.Column("grade", sa.String(length=8), nullable=True),
        sa.Column("credits", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_profile_id"],
            ["student_profiles.id"],
            name=op.f("fk_student_completed_subjects_student_profile_id_student_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_student_completed_subjects_subject_id_subjects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
            name=op.f("fk_student_completed_subjects_term_id_terms"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_completed_subjects")),
        sa.UniqueConstraint(
            "student_profile_id", "subject_id", name="uq_student_completed_subject"
        ),
    )
    op.create_index(
        op.f("ix_student_completed_subjects_student_profile_id"),
        "student_completed_subjects",
        ["student_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_completed_subjects_subject_id"),
        "student_completed_subjects",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_completed_subjects_term_id"),
        "student_completed_subjects",
        ["term_id"],
        unique=False,
    )
    op.create_table(
        "student_in_progress_subjects",
        sa.Column("student_profile_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_profile_id"],
            ["student_profiles.id"],
            name=op.f("fk_student_in_progress_subjects_student_profile_id_student_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_student_in_progress_subjects_subject_id_subjects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
            name=op.f("fk_student_in_progress_subjects_term_id_terms"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_in_progress_subjects")),
        sa.UniqueConstraint("student_profile_id", "subject_id", name="uq_student_progress_subject"),
    )
    op.create_index(
        op.f("ix_student_in_progress_subjects_student_profile_id"),
        "student_in_progress_subjects",
        ["student_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_in_progress_subjects_subject_id"),
        "student_in_progress_subjects",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_in_progress_subjects_term_id"),
        "student_in_progress_subjects",
        ["term_id"],
        unique=False,
    )
    op.create_table(
        "student_preferences",
        sa.Column("student_profile_id", sa.Uuid(), nullable=False),
        sa.Column("hard_constraints", sa.JSON(), nullable=False),
        sa.Column("soft_preferences", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["student_profile_id"],
            ["student_profiles.id"],
            name=op.f("fk_student_preferences_student_profile_id_student_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_preferences")),
    )
    op.create_index(
        op.f("ix_student_preferences_student_profile_id"),
        "student_preferences",
        ["student_profile_id"],
        unique=True,
    )
    op.create_table(
        "student_courses",
        sa.Column("student_profile_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("curriculum_version_id", sa.Uuid(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("cp", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("ik", sa.Numeric(precision=7, scale=6), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_student_courses_course_id_courses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["curriculum_version_id"],
            ["curriculum_versions.id"],
            name=op.f("fk_student_courses_curriculum_version_id_curriculum_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_profile_id"],
            ["student_profiles.id"],
            name=op.f("fk_student_courses_student_profile_id_student_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_courses")),
        sa.UniqueConstraint("student_profile_id", "course_id", name="uq_student_course"),
    )
    op.create_index(
        op.f("ix_student_courses_course_id"), "student_courses", ["course_id"], unique=False
    )
    op.create_index(
        "ix_student_courses_curriculum",
        "student_courses",
        ["curriculum_version_id", "student_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_courses_curriculum_version_id"),
        "student_courses",
        ["curriculum_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_courses_student_profile_id"),
        "student_courses",
        ["student_profile_id"],
        unique=False,
    )
    op.add_column(
        "curriculum_versions",
        sa.Column(
            "unlisted_subject_category",
            sa.Enum(
                "MANDATORY",
                "LIMITED",
                "FREE",
                "NOT_APPLICABLE",
                name="curriculumcategory",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("curriculum_versions", "unlisted_subject_category")
    op.drop_index(op.f("ix_student_courses_student_profile_id"), table_name="student_courses")
    op.drop_index(op.f("ix_student_courses_curriculum_version_id"), table_name="student_courses")
    op.drop_index("ix_student_courses_curriculum", table_name="student_courses")
    op.drop_index(op.f("ix_student_courses_course_id"), table_name="student_courses")
    op.drop_table("student_courses")
    op.drop_index(
        op.f("ix_student_preferences_student_profile_id"), table_name="student_preferences"
    )
    op.drop_table("student_preferences")
    op.drop_index(
        op.f("ix_student_in_progress_subjects_term_id"), table_name="student_in_progress_subjects"
    )
    op.drop_index(
        op.f("ix_student_in_progress_subjects_subject_id"),
        table_name="student_in_progress_subjects",
    )
    op.drop_index(
        op.f("ix_student_in_progress_subjects_student_profile_id"),
        table_name="student_in_progress_subjects",
    )
    op.drop_table("student_in_progress_subjects")
    op.drop_index(
        op.f("ix_student_completed_subjects_term_id"), table_name="student_completed_subjects"
    )
    op.drop_index(
        op.f("ix_student_completed_subjects_subject_id"), table_name="student_completed_subjects"
    )
    op.drop_index(
        op.f("ix_student_completed_subjects_student_profile_id"),
        table_name="student_completed_subjects",
    )
    op.drop_table("student_completed_subjects")
    op.drop_table("student_profiles")
    # ### end Alembic commands ###
