"""allow shared ufabc next subject identifiers

Revision ID: 1fecfaf3a22e
Revises: 27c9e4946f45
Create Date: 2026-07-16 00:43:40.576985
"""

from collections.abc import Sequence

from alembic import op

revision: str = "1fecfaf3a22e"
down_revision: str | None = "27c9e4946f45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_subject_external_provider_id"), "external_subject_identifiers", type_="unique"
    )
    op.create_unique_constraint(
        "uq_subject_external_provider_id_subject",
        "external_subject_identifiers",
        ["provider", "external_id", "subject_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_subject_external_provider_id_subject", "external_subject_identifiers", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_subject_external_provider_id"),
        "external_subject_identifiers",
        ["provider", "external_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
