"""add ufabc next synchronization

Revision ID: 27c9e4946f45
Revises: 83481302fee5
Create Date: 2026-07-16 00:29:45.935535
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "27c9e4946f45"
down_revision: str | None = "83481302fee5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ufabc_next_cache_entries",
        sa.Column("request_key", sa.String(length=64), nullable=False),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ufabc_next_cache_entries")),
    )
    op.create_index(
        op.f("ix_ufabc_next_cache_entries_expires_at"),
        "ufabc_next_cache_entries",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ufabc_next_cache_entries_request_key"),
        "ufabc_next_cache_entries",
        ["request_key"],
        unique=True,
    )
    op.create_table(
        "ufabc_next_sync_runs",
        sa.Column("season", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING",
                "COMPLETED",
                "COMPLETED_WITH_WARNINGS",
                "FAILED",
                name="externalsyncstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("include_teacher_reviews", sa.Boolean(), nullable=False),
        sa.Column("include_subject_reviews", sa.Boolean(), nullable=False),
        sa.Column("force_refresh", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("remote_requests", sa.Integer(), nullable=False),
        sa.Column("cache_hits", sa.Integer(), nullable=False),
        sa.Column("components_received", sa.Integer(), nullable=False),
        sa.Column("components_matched", sa.Integer(), nullable=False),
        sa.Column("components_unmatched", sa.Integer(), nullable=False),
        sa.Column("teacher_reviews_synced", sa.Integer(), nullable=False),
        sa.Column("subject_reviews_synced", sa.Integer(), nullable=False),
        sa.Column("request_log", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ufabc_next_sync_runs")),
    )
    op.create_index(
        "ix_next_sync_runs_season_created",
        "ufabc_next_sync_runs",
        ["season", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ufabc_next_sync_runs_season"), "ufabc_next_sync_runs", ["season"], unique=False
    )
    op.create_index(
        op.f("ix_ufabc_next_sync_runs_status"), "ufabc_next_sync_runs", ["status"], unique=False
    )
    op.create_table(
        "external_subject_identifiers",
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_external_subject_identifiers_subject_id_subjects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_subject_identifiers")),
        sa.UniqueConstraint("provider", "external_id", name="uq_subject_external_provider_id"),
    )
    op.create_index(
        op.f("ix_external_subject_identifiers_subject_id"),
        "external_subject_identifiers",
        ["subject_id"],
        unique=False,
    )
    op.create_table(
        "subject_review_snapshots",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("external_subject_id", sa.String(length=255), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("distribution", sa.JSON(), nullable=False),
        sa.Column("teacher_statistics", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_subject_review_snapshots_subject_id_subjects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["ufabc_next_sync_runs.id"],
            name=op.f("fk_subject_review_snapshots_sync_run_id_ufabc_next_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subject_review_snapshots")),
        sa.UniqueConstraint(
            "sync_run_id", "external_subject_id", name="uq_subject_review_snapshot_run_subject"
        ),
    )
    op.create_index(
        op.f("ix_subject_review_snapshots_external_subject_id"),
        "subject_review_snapshots",
        ["external_subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subject_review_snapshots_fetched_at"),
        "subject_review_snapshots",
        ["fetched_at"],
        unique=False,
    )
    op.create_index(
        "ix_subject_review_snapshots_subject_fetched",
        "subject_review_snapshots",
        ["subject_id", "fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subject_review_snapshots_subject_id"),
        "subject_review_snapshots",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subject_review_snapshots_sync_run_id"),
        "subject_review_snapshots",
        ["sync_run_id"],
        unique=False,
    )
    op.create_table(
        "teacher_review_snapshots",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=True),
        sa.Column("external_teacher_id", sa.String(length=255), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("distribution", sa.JSON(), nullable=False),
        sa.Column("specific_statistics", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["ufabc_next_sync_runs.id"],
            name=op.f("fk_teacher_review_snapshots_sync_run_id_ufabc_next_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
            name=op.f("fk_teacher_review_snapshots_teacher_id_teachers"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_review_snapshots")),
        sa.UniqueConstraint(
            "sync_run_id", "external_teacher_id", name="uq_teacher_review_snapshot_run_teacher"
        ),
    )
    op.create_index(
        op.f("ix_teacher_review_snapshots_external_teacher_id"),
        "teacher_review_snapshots",
        ["external_teacher_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_review_snapshots_fetched_at"),
        "teacher_review_snapshots",
        ["fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_review_snapshots_sync_run_id"),
        "teacher_review_snapshots",
        ["sync_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_teacher_review_snapshots_teacher_fetched",
        "teacher_review_snapshots",
        ["teacher_id", "fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_teacher_review_snapshots_teacher_id"),
        "teacher_review_snapshots",
        ["teacher_id"],
        unique=False,
    )
    op.create_table(
        "ufabc_next_component_snapshots",
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("external_component_id", sa.String(length=255), nullable=True),
        sa.Column("external_section_code", sa.String(length=64), nullable=False),
        sa.Column("external_subject_id", sa.String(length=255), nullable=True),
        sa.Column("seats", sa.Integer(), nullable=True),
        sa.Column("requests", sa.Integer(), nullable=True),
        sa.Column("enrolled_count", sa.Integer(), nullable=False),
        sa.Column("ideal_term", sa.Boolean(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_ufabc_next_component_snapshots_section_id_sections"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_ufabc_next_component_snapshots_subject_id_subjects"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["ufabc_next_sync_runs.id"],
            name=op.f("fk_ufabc_next_component_snapshots_sync_run_id_ufabc_next_sync_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["terms.id"],
            name=op.f("fk_ufabc_next_component_snapshots_term_id_terms"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ufabc_next_component_snapshots")),
        sa.UniqueConstraint(
            "sync_run_id", "external_section_code", name="uq_next_component_snapshot_run_section"
        ),
    )
    op.create_index(
        "ix_next_component_snapshots_external_subject",
        "ufabc_next_component_snapshots",
        ["external_subject_id"],
        unique=False,
    )
    op.create_index(
        "ix_next_component_snapshots_term_section",
        "ufabc_next_component_snapshots",
        ["term_id", "section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ufabc_next_component_snapshots_external_component_id"),
        "ufabc_next_component_snapshots",
        ["external_component_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ufabc_next_component_snapshots_external_section_code"),
        "ufabc_next_component_snapshots",
        ["external_section_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ufabc_next_component_snapshots_section_id"),
        "ufabc_next_component_snapshots",
        ["section_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ufabc_next_component_snapshots_subject_id"),
        "ufabc_next_component_snapshots",
        ["subject_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ufabc_next_component_snapshots_sync_run_id"),
        "ufabc_next_component_snapshots",
        ["sync_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ufabc_next_component_snapshots_term_id"),
        "ufabc_next_component_snapshots",
        ["term_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ufabc_next_component_snapshots_term_id"),
        table_name="ufabc_next_component_snapshots",
    )
    op.drop_index(
        op.f("ix_ufabc_next_component_snapshots_sync_run_id"),
        table_name="ufabc_next_component_snapshots",
    )
    op.drop_index(
        op.f("ix_ufabc_next_component_snapshots_subject_id"),
        table_name="ufabc_next_component_snapshots",
    )
    op.drop_index(
        op.f("ix_ufabc_next_component_snapshots_section_id"),
        table_name="ufabc_next_component_snapshots",
    )
    op.drop_index(
        op.f("ix_ufabc_next_component_snapshots_external_section_code"),
        table_name="ufabc_next_component_snapshots",
    )
    op.drop_index(
        op.f("ix_ufabc_next_component_snapshots_external_component_id"),
        table_name="ufabc_next_component_snapshots",
    )
    op.drop_index(
        "ix_next_component_snapshots_term_section", table_name="ufabc_next_component_snapshots"
    )
    op.drop_index(
        "ix_next_component_snapshots_external_subject", table_name="ufabc_next_component_snapshots"
    )
    op.drop_table("ufabc_next_component_snapshots")
    op.drop_index(
        op.f("ix_teacher_review_snapshots_teacher_id"), table_name="teacher_review_snapshots"
    )
    op.drop_index(
        "ix_teacher_review_snapshots_teacher_fetched", table_name="teacher_review_snapshots"
    )
    op.drop_index(
        op.f("ix_teacher_review_snapshots_sync_run_id"), table_name="teacher_review_snapshots"
    )
    op.drop_index(
        op.f("ix_teacher_review_snapshots_fetched_at"), table_name="teacher_review_snapshots"
    )
    op.drop_index(
        op.f("ix_teacher_review_snapshots_external_teacher_id"),
        table_name="teacher_review_snapshots",
    )
    op.drop_table("teacher_review_snapshots")
    op.drop_index(
        op.f("ix_subject_review_snapshots_sync_run_id"), table_name="subject_review_snapshots"
    )
    op.drop_index(
        op.f("ix_subject_review_snapshots_subject_id"), table_name="subject_review_snapshots"
    )
    op.drop_index(
        "ix_subject_review_snapshots_subject_fetched", table_name="subject_review_snapshots"
    )
    op.drop_index(
        op.f("ix_subject_review_snapshots_fetched_at"), table_name="subject_review_snapshots"
    )
    op.drop_index(
        op.f("ix_subject_review_snapshots_external_subject_id"),
        table_name="subject_review_snapshots",
    )
    op.drop_table("subject_review_snapshots")
    op.drop_index(
        op.f("ix_external_subject_identifiers_subject_id"),
        table_name="external_subject_identifiers",
    )
    op.drop_table("external_subject_identifiers")
    op.drop_index(op.f("ix_ufabc_next_sync_runs_status"), table_name="ufabc_next_sync_runs")
    op.drop_index(op.f("ix_ufabc_next_sync_runs_season"), table_name="ufabc_next_sync_runs")
    op.drop_index("ix_next_sync_runs_season_created", table_name="ufabc_next_sync_runs")
    op.drop_table("ufabc_next_sync_runs")
    op.drop_index(
        op.f("ix_ufabc_next_cache_entries_request_key"), table_name="ufabc_next_cache_entries"
    )
    op.drop_index(
        op.f("ix_ufabc_next_cache_entries_expires_at"), table_name="ufabc_next_cache_entries"
    )
    op.drop_table("ufabc_next_cache_entries")
    # ### end Alembic commands ###
