"""add explainable section rankings

Revision ID: ed7692a809a4
Revises: 1acc84acc4a0
Create Date: 2026-07-16 01:35:55.125276
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ed7692a809a4"
down_revision: str | None = "1acc84acc4a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rankings",
        sa.Column("term_id", sa.Uuid(), nullable=False),
        sa.Column("student_profile_id", sa.Uuid(), nullable=False),
        sa.Column("source_ranking_id", sa.Uuid(), nullable=True),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("result_limit", sa.Integer(), nullable=False),
        sa.Column("candidate_count", sa.Integer(), nullable=False),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_ranking_id"],
            ["rankings.id"],
            name=op.f("fk_rankings_source_ranking_id_rankings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["student_profile_id"],
            ["student_profiles.id"],
            name=op.f("fk_rankings_student_profile_id_student_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["term_id"], ["terms.id"], name=op.f("fk_rankings_term_id_terms"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rankings")),
    )
    op.create_index(op.f("ix_rankings_computed_at"), "rankings", ["computed_at"], unique=False)
    op.create_index(
        op.f("ix_rankings_source_ranking_id"), "rankings", ["source_ranking_id"], unique=False
    )
    op.create_index(
        op.f("ix_rankings_student_profile_id"), "rankings", ["student_profile_id"], unique=False
    )
    op.create_index(
        "ix_rankings_student_term_computed",
        "rankings",
        ["student_profile_id", "term_id", "computed_at"],
        unique=False,
    )
    op.create_index(op.f("ix_rankings_term_id"), "rankings", ["term_id"], unique=False)
    op.create_table(
        "ranking_items",
        sa.Column("ranking_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("score_breakdown", sa.JSON(), nullable=False),
        sa.Column("section_snapshot", sa.JSON(), nullable=False),
        sa.Column("curriculum_classifications", sa.JSON(), nullable=False),
        sa.Column("teacher_statistics", sa.JSON(), nullable=False),
        sa.Column("seat_probability", sa.JSON(), nullable=False),
        sa.Column("explanations", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["ranking_id"],
            ["rankings.id"],
            name=op.f("fk_ranking_items_ranking_id_rankings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_ranking_items_section_id_sections"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ranking_items")),
        sa.UniqueConstraint("ranking_id", "position", name="uq_ranking_item_position"),
        sa.UniqueConstraint("ranking_id", "section_id", name="uq_ranking_item_section"),
    )
    op.create_index(
        op.f("ix_ranking_items_ranking_id"), "ranking_items", ["ranking_id"], unique=False
    )
    op.create_index(
        "ix_ranking_items_ranking_score",
        "ranking_items",
        ["ranking_id", "total_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ranking_items_section_id"), "ranking_items", ["section_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ranking_items_section_id"), table_name="ranking_items")
    op.drop_index("ix_ranking_items_ranking_score", table_name="ranking_items")
    op.drop_index(op.f("ix_ranking_items_ranking_id"), table_name="ranking_items")
    op.drop_table("ranking_items")
    op.drop_index(op.f("ix_rankings_term_id"), table_name="rankings")
    op.drop_index("ix_rankings_student_term_computed", table_name="rankings")
    op.drop_index(op.f("ix_rankings_student_profile_id"), table_name="rankings")
    op.drop_index(op.f("ix_rankings_source_ranking_id"), table_name="rankings")
    op.drop_index(op.f("ix_rankings_computed_at"), table_name="rankings")
    op.drop_table("rankings")
    # ### end Alembic commands ###
